services:
  django-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8004:8000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: zamazon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zamazon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - mypostgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
      - django-web
    volumes:
      - .:/src


volumes:
  mypostgres_data: