services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8004:8000"
    container_name: DjBackend
    depends_on:
      - myredis
      - db
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: zamazon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
  db:
    image: postgres:latest
    container_name: za_postgres_db
    restart: always 
    environment:
      POSTGRES_DB: zamazon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - mypostgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  myredis:
    image: redis:7.4.2-alpine
    container_name: MyRedisServer
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - myredis
      - backend
    volumes:
      - .:/src


volumes:
  mypostgres_data: