# Generated by Django 4.2.19 on 2025-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company_android_ios_app_company_free_home_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='product_fee')),
            ],
        ),
    ]
