# Generated by Django 4.2.19 on 2025-02-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_feeoffer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeOffer',
            new_name='FreeOffer',
        ),
    ]
