# Generated by Django 4.2.19 on 2025-02-18 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_feeoffer_freeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
