# Generated by Django 4.2.19 on 2025-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_freeoffer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfee',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
